### PR TITLE
[misc] Update dependencies and formatting

### PR DESCRIPTION
**Pull request by slarse**
Updates a bunch of dependencies and the autoformatting (which was seemingly broken).

### CODE REVIEW

**Comment by slarse** [comment]
Thanks @monperrus for giving the CI some love, this PR should fix the rest :)

**Comment by monperrus** [comment]
Never enough :heart: for code to stay afloat in the dependency rapids.

**Comment by monperrus** [comment]
Bumping gt-spoon is breaking https://github.com/ASSERT-KTH/spork/pull/458

To be expected because of the underlying udate to Gumtree v3.

It would be great to port it, and Jean-Remy had ideas about the usage of GT3 in Spork.

**Comment by slarse** [comment]
I'll try to find some time to give it a try, but my guess is that there's some amount of work involved in doing it. Spork makes use of a whole lot of implementation details, both explicitly and implicitly :)

**Comment by monperrus** [comment]
agree, that may be quite hard work.

**Pull request merged**
